version: '3'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: "user"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DB: "database"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
volumes:
  clickhouse_data: